apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: resultserver-deployment
  name: resultserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: resultserver-deployment
    spec:
      containers:
      - image: korayayakin/pyappresserv:v1
        name: pyappresserv
        ports:
        - containerPort: 80
        resources: {}
        envFrom:
        - configMapRef: 
            name: serverconfigmap
        env:
          - name: MYSQL_PASSWORD
            valueFrom: 
              secretKeyRef:
                key: MYSQL_PASSWORD
                name: mysecret 


            

status: {}
